version : '3.1'
services:  
  postgres:
    image: postgres:11
    container_name: bankpg
    environment:
      TZ: "America/Mexico_City"
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: bank.2444
      POSTGRES_DB: db_bank
    ports:
      - "65432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: bankdj
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    command: python manage.py makemigrations
    command: python manage.py migrate
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      POSTGRES_DB_NAME: 'db_bank'
      POSTGRES_DB_USER: 'postgres'
      POSTGRES_DB_PASSWORD: 'bank.2444'
      POSTGRES_SERVICE_HOST: 'bankpg'
      POSTGRES_SERVICE_PORT: '65432'
    volumes:
      - .:/django_app
volumes:
  postgres_data:   
  
