# Generated by Django 4.1 on 2022-08-12 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=50, verbose_name='numero de cuenta')),
                ('date', models.CharField(max_length=10, verbose_name='fecha')),
                ('transaccion', models.CharField(max_length=250, verbose_name='transaction')),
            ],
            options={
                'db_table': 'transaction',
            },
        ),
    ]
